# handlers file for elk
---
- name: Restart packetbeat
  ansible.builtin.systemd:
    name: packetbeat
    state: restarted
    enabled: true

- name: Restart metricbeat
  ansible.builtin.systemd:
    name: metricbeat
    state: restarted

- name: Restart filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true

- name: Restart heartbeat
  ansible.builtin.systemd:
    name: heartbeat
    state: restarted
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true